2주차 내용 정리
stemmmm/java-study pull request #11
Opened 2024-08-02 16:52 UTC by jij0128

2주차 내용 정리했습니다.

설명이 부족하다거나 추가하면 좋을 내용이 있다면 알려주세요

2024-08-03 09:12 UTC, stemmmm requested changes
고생했습니다~
다만, 전체적으로 코드가 좀 더 작성되었으면 좋겠습니다

2024-08-03 09:12 UTC, stemmmm commented on basic/src/main/java/study/week2/section07/injejeong/README.md
> +- 후입선출(LIFO, Last In First Out) 방식 → 나중에 넣은 것이 가장 먼저 나오는 자료 구조
자료구조 스택과 메모리의 스택 영역은 같은걸까요?
마찬가지로 자료구조 힙과 메모리의 힙 영역은 같은걸까요?

2024-08-03 09:12 UTC, stemmmm commented on basic/src/main/java/study/week2/section07/injejeong/README.md
> +- 가비지 컬렉션으로 메모리 관리
가비지 컬렉션이 무엇인가요?

2024-08-03 09:12 UTC, stemmmm commented on basic/src/main/java/study/week2/section07/injejeong/README.md
> +- static 변수는 인스턴스를 만들 때 마다 생성되는 인스턴스 변수와 다르게 프로그램 시작 시 1번만 생성됨
`static` 변수나 메서드는 메모리의 어떤 영역에 저장될까요?

2024-08-03 09:12 UTC, stemmmm commented on basic/src/main/java/study/week2/section08/injejeong/README.md
> +  - `static` 영역은 하나만 존재하기 때문에, 메모리 낭비 방지와 중복 제거 가능
`final`을 클래스에 붙이면 어떤 동작을 하나요~?

2024-08-03 09:12 UTC, stemmmm commented on basic/src/main/java/study/week2/section08/injejeong/README.md
> +- 최초 한 번만 값 할당 가능, 이후 재할당 시도 시 컴파일 오류 발생
컴파일 오류란 무엇일까요?

2024-08-03 09:12 UTC, stemmmm commented on basic/src/main/java/study/week2/section09/injejeong/README.md
상속을 활용한 코드를 작성해주세요~

2024-08-03 09:12 UTC, stemmmm commented on basic/src/main/java/study/week2/section09/injejeong/README.md
> +- `@Override` 키워드 밑에서 해당 메서드 재정의
`@Override` 키워드를 붙이면 붙이지 않는것과 어떤점이 다르나요?

2024-08-03 09:12 UTC, stemmmm commented on basic/src/main/java/study/week2/section10/injejeong/README.md
다형성을 활용한 코드를 작성해주세요~

2024-08-03 09:12 UTC, stemmmm commented on basic/src/main/java/study/week2/section11/injejeong/README.md
> +}
indentation 맞춰주세요!

2024-08-03 09:12 UTC, stemmmm commented on basic/src/main/java/study/week2/section11/injejeong/README.md
> +- 순수 추상 클래스를 더 편리하게 사용할 수 있도록 해줌
언제 인터페이스를 사용하고 언제 추상 클래스를 사용하는게 적절할까요?

2024-08-03 09:12 UTC, stemmmm commented on basic/src/main/java/study/week2/section12/injejeong/README.md
> +```
indentation 맞춰주세요~
`Car`를 구현하는 다른 클래스를 만들어보고, `Driver`에서 어떻게 사용할 수 있을지 코드로 작성해보세요

2024-08-06 08:08 UTC, jij0128 commented on basic/src/main/java/study/week2/section07/injejeong/README.md
> +- 후입선출(LIFO, Last In First Out) 방식 → 나중에 넣은 것이 가장 먼저 나오는 자료 구조
자료구조 스택은 데이터를 저장하는 구조로, 후입선출의 방식으로 데이터가 쌓이고 제거됩니다.
메모리의 스택 영역은 프로그램이 실행될 때 사용되는 메모리 영역 중 하나로, 함수 호출 시 지역 변수나 매개변수 등을 저장하는 용도로 사용됩니다.

자료구조 힙은 최댓값 또는 최솟값을 빠르게 찾기 위해 사용되는 트리 기반의 자료구조입니다.
메모리의 힙 영역은 프로그램 실행 중 동적으로 할당된 메모리를 관리하는 영역입니다. 동적 메모리 할당을 통해 힙 영역에 데이터를 저장하고 해제할 수 있습니다.

2024-08-06 08:08 UTC, jij0128 commented on basic/src/main/java/study/week2/section07/injejeong/README.md
> +- 가비지 컬렉션으로 메모리 관리
가비지 컬렉션은 JVM(Java Virtual Machine)의 일부이며 자동 메모리 관리 기법 중 하나로, 프로그램 실행 시 동적으로 할당한 메모리 영역 중에서 더 이상 사용되지 않는 객체들을 자동으로 인식하고 해제하는 프로세스입니다.

2024-08-06 08:08 UTC, jij0128 commented on basic/src/main/java/study/week2/section07/injejeong/README.md
> +- static 변수는 인스턴스를 만들 때 마다 생성되는 인스턴스 변수와 다르게 프로그램 시작 시 1번만 생성됨
static 변수와 static 메서드는 메모리의 메서드 영역에 저장됩니다. 메서드 영역은 JVM이 시작될 때 생성되며, 모든 쓰레드에서 공유됩니다.

2024-08-06 08:08 UTC, jij0128 commented on basic/src/main/java/study/week2/section08/injejeong/README.md
> +  - `static` 영역은 하나만 존재하기 때문에, 메모리 낭비 방지와 중복 제거 가능
final 키워드를 클래스에 붙이면 해당 클래스는 상속을 금지하는 효과를 가집니다.

2024-08-06 08:08 UTC, jij0128 commented on basic/src/main/java/study/week2/section08/injejeong/README.md
> +- 최초 한 번만 값 할당 가능, 이후 재할당 시도 시 컴파일 오류 발생
컴파일 오류란 소스 코드를 컴파일하는 과정에서 발생하는 오류를 말합니다. 이러한 오류는 일반적으로 코드 문법이 잘못된 경우, 타입 오류(type error), 선언되지 않은 변수나 메서드 사용 등과 같은 논리적 오류 때문에 발생할 수 있습니다.

2024-08-06 08:08 UTC, jij0128 commented on basic/src/main/java/study/week2/section09/injejeong/README.md
> +- `@Override` 키워드 밑에서 해당 메서드 재정의
`@Override` 키워드는 메서드 선언 앞에 붙여서 사용할 수 있는 어노테이션으로, 컴파일러가 해당 메서드가 부모 클래스나 인터페이스의 메서드를 오버라이드하려는 것임을 검사하고, 만약 실제로 오버라이드하는 메서드가 아니라면 컴파일 오류를 발생시킵니다.

@Override 어노테이션은 코드의 안정성과 가독성을 높이는 데 기여하므로, 명시적으로 붙이는 것이 좋습니다.

2024-08-06 08:09 UTC, jij0128 commented on basic/src/main/java/study/week2/section11/injejeong/README.md
> +- 순수 추상 클래스를 더 편리하게 사용할 수 있도록 해줌
다중 상속을 해야 할 경우 인터페이스를 사용합니다. 자바는 단일 상속만 지원하므로, 인터페이스를 사용하여 다중 상속을 구현할 수 있습니다.

공통된 구현이 필요한 경우 추상 클래스를 사용합니다. 여러 서브 클래스들이 공통적인 기능을 가질 경우, 추상 클래스를 사용하여 공통 메서드를 구현하고 서브 클래스들에게 상속할 수 있습니다.

2024-08-06 08:13 UTC, jij0128 commented on basic/src/main/java/study/week2/section11/injejeong/README.md
> +}
수정했습니다~

2024-08-06 08:33 UTC, jij0128 commented on basic/src/main/java/study/week2/section10/injejeong/README.md
작성하여 추가했습니다.

2024-08-06 08:37 UTC, jij0128 commented on basic/src/main/java/study/week2/section12/injejeong/README.md
> +```
추가했습니다.

2024-08-06 12:24 UTC, jij0128 commented on basic/src/main/java/study/week2/section09/injejeong/README.md
추가했습니다

2024-08-06 12:44 UTC, stemmmm approved these changes
LGTM

2024-08-06 12:44 UTC, merged